#!/usr/bin/with-contenv sh

#!/usr/bin/execlineb -P
fdmove -c 2 1 /code/start-www.sh

with-contenv

#!/usr/bin/execlineb -P
# fdmove -c 2 1 
# s6-setuidgid fluent 
# fluentd -c /fluentd/etc/fluent.conf -p /fluentd/plugins -v



